### ISSUE TITLE
The docs don’t seem to work

### ISSUE THREAD

**Issue by IgnusG** [bothelljs/docs#1]
It just displays a message about rocket docs and gatsby on every page:

![D4696CD3-6DA8-471D-922A-8E725F3855E3](https://user-images.githubusercontent.com/6438760/142707664-cbed7d4f-e1a4-4343-8ea0-f2982a1dcef4.jpeg)

**Comment by joelerego** [comment]
Hey. The docs and the library is not complete yet. Apologies. Will update the docs soon.
